name: em-workshop-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - rioxarray
  - matplotlib
  - icechunk
  - jupyterlab
  - zarr
  - geopandas
  - odc-geo
  - dask
  - flox
  - contextily
  - pip:
      - git+https://github.com/dcherian/xarray.git@cng-workshop
