name: em-workshop-env
channels:
  - conda-forge
dependencies:
  - rioxarray>=0.19.0,<1.0.0
  - matplotlib>=3.10.1,<4.0.0
  - icechunk>=0.2.15,<1.0.0
  - jupyterlab
  - zarr>=3.0.7,<4.0.0
  - leafmap>=0.43.6,<1.0.0
  - localtileserver>=0.10.6,<1.0.0
  - hvplot>=0.11.2,<1.0.0
  - geoviews>=1.14.0,<2.0.0
  - datashader>=0.18.0,<1.0.0
  - jupyter_bokeh>=4.0.5,<5.0.0
  - dask>=2025.4.0,<2026.0.0
  - geopandas>=1.0.1,<2.0.0
  - odc-geo>=0.4.10,<1.0.0
  - flox>=0.10.3,<1.0.0
  - contextily>=1.6.2,<2.0.0
  - netcdf4>=1.26.4,<2.0.0
  - boto3==1.33.2
  - pip  # add pip so pip dependencies can be installed
  - pip:
      - git+https://github.com/dcherian/xarray.git@cng-workshop
